Feature/basic interfaces
ECASLab/cynq pull request #4
Opened 2023-11-05 23:53 UTC by dierpg

This pr adds the following header files and its documentation:
1. accelerator.hpp
2. datamover.hpp
3. hardware.hpp
4. status.hpp
5. memory.hpp

This can be found within the /include/cynq directory and are used
by inheritors that implement the cynq api.

2023-11-06 10:42 UTC, lleon95 requested changes

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/accelerator.hpp
> +class IAccelerator {
Document the class

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/accelerator.hpp
> +  virtual ~IAccelerator() {}
you can use `virtual ~IAccelerator() = default;` instead.

Also, document it. Apply to all occurrences

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/accelerator.hpp
> +   * This starts the accelerator.
You can elaborate more on the "mode". For instance:

```
This method starts the accelerator in either once or continuous mode (with the autorestart). Under the hood, this writes the control register to turn on the accelerator with/without the autorestart bit.
```

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/accelerator.hpp
> +   * This stops the accelerator.
This asynchronously turns off the accelerator by removing the autorestart and start bits from the control registers. Please, note that the accelerator will turn off once it finishes its current task.

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/accelerator.hpp
> +   * DeviceStatus enum class present in the enums.hpp file.
This returns the accelerator state by using the DeviceStatus. This reads the control register flags.

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/accelerator.hpp
> +  virtual Status WriteRegister(const uint64_t address, uint64_t *data,
The data pointer is actually `uint8_t`, which is the minimum unit to transfer

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/accelerator.hpp
> +  virtual Status ReadRegister(const uint64_t address, uint64_t *data,
Same here

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/accelerator.hpp
> +}
Missing `;`. Did you override the pre-commit hooks?

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/datamover.hpp
> +  virtual ~IDataMover() {}
Same comments. Document the class and the destructor

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/datamover.hpp
> +   * Retrieves the buffer used for mapping the data to memory.
This is a bit inaccurate.

```
This method allocates a memory buffer. Depending on the MemoryType (elaborate more...), it allocates memory in a contiguous memory region (non-pageable). The memory can be mirrored with pageable memory for its use in the host (or CPU).
```

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/datamover.hpp
> +   * present in the enums.hpp file
Elaborate more... Remember when you complain when reading inaccurate documentation.

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/datamover.hpp
> +   * Writes the data in the buffer to the IMemory instance in the argument.
Which data?

The description is inaccurate.

```
This method moves the data from the host to the device using a DMA engine. This triggers the AXI Memory Map and AXI Stream Transactions under the hood
```

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/datamover.hpp
> +   * @param mem IMemory instance to write.
to upload*

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/datamover.hpp
> +   * @param exetype One of the values in the ExecutionType enum class
Try to be more explicit...

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/datamover.hpp
> +   * Synchronizes data contents of buffer.
Synchronises the data movements in case of asynchronous Upload/Download.

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/datamover.hpp
> +   * DeviceStatus enum class present in the enums.hpp file.
Returns the status of the data mover in terms of transactions.

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/datamover.hpp
> +}
Missing `;`.

Moreover, the Download method is missing

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/status.hpp
> +struct Status {
Please, add this into the `cynq` namespace

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/memory.hpp
> +  virtual std::shared_ptr<uint64_t> GetHostAddress() = 0;
The data type must be `uint8_t`

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/memory.hpp
> +  virtual std::shared_ptr<uint64_t> GetDeviceAddress() = 0;
The data type must be `uint8_t`

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/memory.hpp
> +   * Synchronizes the memory.
Be more explicit. The synchronisation types are from host to device to vice-versa. Be more explicit

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/memory.hpp
> +   * present in the enums.hpp file.
Same here. Remember accuracy in the documentation

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/memory.hpp
> +  virtual ~IMemory() {}
Missing documentation

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/memory.hpp
> +   * @return std::shared_ptr<uint64_t>
Add:

[Reference] shared memory pointer with reference counting

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/memory.hpp
> +   * @return std::shared_ptr<uint64_t>
Add:

[Reference] shared memory pointer with reference counting

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/hardware.hpp
> +#include "cynq/status.hpp"
Missing headers. You are using the datamover and accelerator

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/datamover.hpp
> +#include "cynq/status.hpp"
Missing headers, you are using the memory header

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/hardware.hpp
> +  virtual ~IHardware() {}
Document the destructor

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/hardware.hpp
> +   * Sets the IHardware instance to its initital state.
Initial*

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/hardware.hpp
> +   * @param address a unsigned integer of 64 bits represeting an address.
representing*

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/hardware.hpp
> +   * IHardware inheritors.
Elaborate. Why we want a DataMover?

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/hardware.hpp
> +   * IDataMover instance of IAccelerator inheritors.
Same here

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/hardware.hpp
> +   * @return std::shared_ptr<IDataMover>
Returns an IDataMover pointer with reference counting. It should be thread-safe

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/hardware.hpp
> +   * @return std::shared_ptr<IAccelerator>
Returns an IDataMover pointer with reference counting. It should be thread-safe

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/hardware.hpp
> +   * present in the enums.hpp file.
Elaborate. What one of the values even mean?

2023-11-06 10:42 UTC, lleon95 commented on include/cynq/hardware.hpp
> +   * @return std::shared_ptr<IHardware>
Same comment about shared pointers

2023-11-06 23:56 UTC, dierpg commented on include/cynq/hardware.hpp
> +   * IHardware inheritors.
Separation of concerns.

2023-11-07 08:43 UTC, lleon95 requested changes

2023-11-07 08:43 UTC, lleon95 commented on include/cynq/datamover.hpp
> +   * Cacheable (cachce)
cache*

2023-11-07 08:43 UTC, lleon95 commented on include/cynq/hardware.hpp
> +#include "cynq/status.hpp"
Missing accelerador

2023-11-07 22:08 UTC, lleon95 approved these changes

2023-11-08 00:08 UTC, merged